### ISSUE TITLE
First page columns (От редактора) Design with CRUD article functionality for Alex Etman

### ISSUE THREAD

**Issue by AndriyShepitsen** [ChicagoBusinessIntelligence1/svet-newspaper-material#70]
With radio programs interface.

**Comment by ChicagoBusinessIntelligence1** [comment]
Example: http://www.spasibous.com/community

**Comment by ChicagoBusinessIntelligence1** [comment]
Article are displayed by week on the home page. Inside sections  news will be displayed by the topic for a current year
